### ISSUE TITLE
Testing https://jio-frontend.vercel.app on Godwoken Testnet V1

### ISSUE THREAD

**Issue by Kuzirashi** [JioSwap/jio-contracts-deployed#6]
Hi there, I see you submitted your app for Nervos Gitcoin Bounty. I can't do any transaction in your application using the private key you gave. It looks like every transaction is failing. Can you show video showing your application is actually working on Godwoken Testnet V1? Thank you.

cc @dezzyboy

**Comment by dezzyboy** [comment]
hey thanks for the quick response, and i had uploaded a video yesterday located here https://youtu.be/eJBTBWxUB4s
however, theres some optimization im working on as the  transactions are currently slow and you may have to speed up tx in metamask.

**Comment by Kuzirashi** [comment]
Thank you! Will try again!

**Comment by dezzyboy** [comment]
np. just to note : as of now setting a higher gas limit  solves the issue. working on applying a fix

**Comment by dezzyboy** [comment]
update:
New video link to testing jioswap on godwokenV1 : https://youtu.be/Ha8OYVLZi6c
 @Kuzirashi

**Comment by Kuzirashi** [comment]
Thanks, I successfully tested adding liquidity and swap.

**Comment by dezzyboy** [comment]
great will go ahead and close this issue thanks
